---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: right-os
description: right right OS image.

base-image: ghcr.io/blue-build/base-images/fedora-cosmic
image-version: latest

platforms:
  - linux/amd64/v2

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - bieszczaders/kernel-cachyos
        - bieszczaders/kernel-cachyos-addons
    install:
      packages:
        - libdnf5-plugin-actions
        - git
        - kernel-cachyos
        - neovim
        - scx-manager
        - scx-scheds
        - scx-tools
        - starship
        - zsh
    remove:
      packages:
        - kernel
        - kernel-core
        - kernel-modules
        - kernel-modules-core
        - kernel-modules-extra
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-addons
        packages:
          - old: ram-generator-defaults
            new: cachyos-settings
            allow-erasing: true

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.github.rafostar.Clapper
          - com.github.tchx84.Flatseal
          - com.google.Chrome
          - com.ranfdev.DistroShelf
          - io.github.flattool.Warehouse
          - io.github.kolunmi.Bazaar
          - io.missioncenter.MissionCenter
          - io.podman_desktop.PodmanDesktop
      - scope: user

  - type: script
    scripts:
      - 1-password.sh
      - cachyos-kernel-default.sh

  - type: soar
    additional-repos: true
    auto-upgrade: true
    upgrade-interval: '12h'

  - type: justfiles
    validate: true
    install: true
    include:
      - shell.just

  - type: signing
